[versions]
androidGradlePlugin = "8.7.3"
androidTools = "31.4.0"
androidxActivity = "1.9.0"
androidxHiltNavigationCompose = "1.2.0"
androidxComposeBom = "2024.05.00"
androidxComposeCompiler = "2.1.20"  # Compose VC
androidxLifecycle = "2.8.0"
androidxNavigation = "2.8.0-beta01"
baseJunit = "4.13.2"
coreKtxVersion = "1.13.1"
espressoCore = "3.5.1"
hilt = "2.54"
junit4 = "4.13.2"
junit = "1.1.5"
kotlin = "2.1.20"
kotlinxSerializationJson = "1.6.3"
ksp = "2.1.20-2.0.0"
appcompat = "1.7.0"
loggingInterceptor = "5.0.0-alpha.11"
material = "1.12.0"
mpandroidchart = "v3.1.0"
pagingRuntime = "3.3.2"
pagingCompose = "3.3.2"
room = "2.7.0"
kotlinxCoroutines = "1.10.1"
foundationLayoutAndroid = "1.6.7"
retrofit = "2.11.0"
gson = "2.11.0"
retrofitKotlinxSerializationJson = "1.0.0"
accompanist = "0.37.3"
coil = "2.7.0"
roomPaging = "2.7.1"

[libraries]
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "pagingRuntime" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "roomPaging" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material-icon-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
coil-kt = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-kt-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-kt-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }
javax-inject = { module = "javax.inject:javax.inject", version = "1" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-kotlin-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
#coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
#coil-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
#accompanist = { group = "com.google.accompanist", name = "accompanist-placeholder-material", version.ref = "accompanist" }
# Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
# End

# Testing
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
# End

# Hilt
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
# End

# Kotlin
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
# End

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtxVersion" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
junit = { group = "junit", name = "junit", version.ref = "baseJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }
androidx-foundation-layout-android = { group = "androidx.compose.foundation", name = "foundation-layout-android", version.ref = "foundationLayoutAndroid" }
# End

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
room = { id = "androidx.room", version.ref = "room" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

# Plugins defined by this project
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
linker-android-application = { id = "linker.android.application", version = "unspecified" }
linker-android-application-compose = { id = "linker.android.application.compose", version = "unspecified" }
linker-android-library = { id = "linker.android.library", version = "unspecified" }
linker-android-library-compose = { id = "linker.android.library.compose", version = "unspecified" }
linker-android-feature = { id = "linker.android.feature", version = "unspecified" }
linker-android-hilt = { id = "linker.android.hilt", version = "unspecified" }
linker-android-room = { id = "linker.android.room", version = "unspecified" }
# End
